spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/education
    username: my-user
    password: 123456

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
    port: 8083

